version: 2.1
orbs:
  ci-go: ipfs/ci-go@0.2.9

trigger-testplans:
  description: |
    Trigger `graphsync` test cases on TaaS
  executor: << parameters.executor >>
  steps:
    - install-deps
    - prepare
    - run:
        name: "download testground"
        command: wget https://gist.github.com/nonsense/5fbf3167cac79945f658771aed32fc44/raw/2e17eb0debf7ec6bdf027c1bdafc2c92dd97273b/testground-d3e9603 -O ~/testground-cli && chmod +x ~/testground-cli
    - run:
        name: "prepare .env.toml"
        command: pushd testplans/graphsync && mkdir -p $HOME/testground && cp env-ci.toml $HOME/testground/.env.toml && echo 'endpoint="https://ci.testground.ipfs.team"' >> $HOME/testground/.env.toml && echo 'user="circleci"' >> $HOME/testground/.env.toml
    - run:
        name: "prepare testground home dir"
        command: mkdir -p $HOME/testground/plans && mv testplans/graphsync $HOME/testground/plans/
    - run:
        name: "trigger graphsync testplan on taas"
        command: ~/testground-cli run composition -f $HOME/testground/plans/graphsync/_compositions/stress.toml --metadata-commit=$CIRCLE_SHA1 --metadata-repo=ipfs/go-graphsync --metadata-branch=$CIRCLE_BRANCH

workflows:
  version: 2
  test:
    jobs:
      - ci-go/build
      - ci-go/lint
      - ci-go/test
      - ci-go/test:
          race: true
          name: "ci-go/test/race"
      - trigger-testplans
      #- ci-go/benchmark:
      #    tolerance: 50
      #    requires:
      #      - ci-go/test
