[metadata]
name = "stress"

[global]
plan = "graphsync"
case = "stress"
total_instances = 2
builder = "docker:go"
runner = "local:docker"

[global.run.test_params]
size      = "100MB"
latencies = '["200ms"]'
bandwidths = '[]'
concurrency = "1"
chunk_size = "20"
links_per_level = "1024"
raw_leaves = "true"
disk_store = "true"
memory_snapshots = "none"

[[groups]]
id = "providers"
instances = { count = 1 }

[[groups]]
id = "requestors"
instances = { count = 1 }